### ISSUE TITLE
throwing this on 1.16.3 core and hunter is up to date.

### ISSUE THREAD

**Issue by RexyTheDev** [alexsatellite/HeadHunter#25]
[23:46:31 INFO]: [HeadHunter] Enabling HeadHunter v2.1.0
[23:46:31 INFO]: [HeadHunter 2.1.0]  === STARTING ACTIVATION ===
[23:46:33 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_16_R2! Trying to find NMS support
[23:46:33 WARN]: [NBTAPI] [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
[23:46:33 ERROR]: Error occurred while enabling HeadHunter v2.1.0 (Is it up to date?)
de.tr7zw.nbtapi.NbtApiException: Error while calling the method 'null', loaded: false.
        at de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:149) ~[?:?]
        at de.tr7zw.nbtapi.NBTItem.getCompound(NBTItem.java:33) ~[?:?]
        at de.tr7zw.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:468) ~[?:?]
        at de.tr7zw.nbtapi.NBTCompound.setString(NBTCompound.java:68) ~[?:?]
        at me.ByteMagic.HeadHunter.managers.HeadHunter.skulls.MaskSkull.<init>(MaskSkull.java:63) ~[?:?]
        at me.ByteMagic.HeadHunter.managers.HeadHunter.HeadHunterMap.loadMasks(HeadHunterMap.java:115) ~[?:?]
        at me.ByteMagic.HeadHunter.managers.HeadHunter.HeadHunterMap.init(HeadHunterMap.java:69) ~[?:?]
        at me.ByteMagic.HeadHunter.managers.HeadHunter.HeadHunterMap.setActive(HeadHunterMap.java:40) ~[?:?]
        at me.ByteMagic.HeadHunter.managers.HeadHunter.HeadHunterMap.setActive(HeadHunterMap.java:34) ~[?:?]
        at me.ByteMagic.Helix.plugin.BPlugin.activate(BPlugin.java:54) ~[?:?]
        at me.ByteMagic.HeadHunter.Main.preEnable(Main.java:120) ~[?:?]
        at me.ByteMagic.HeadHunter.Main.onEnableInner(Main.java:76) ~[?:?]
        at me.ByteMagic.Helix.plugin.BPlugin.onEnable(BPlugin.java:35) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-232]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-232]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-232]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-232]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-232]        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-232]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:147) ~[?:?]
        ... 22 more
[23:46:33 INFO]: [HeadHunter] Disabling HeadHunter v2.1.0

**Comment by VideoConnected** [comment]
Having the same Issue as well if you have found a solution Please let me know asap as I just recently purchased this thinking It'd be up to date for 1.16.2 and it apparently Isn't I'll try anything at this point

**Comment by VideoConnected** [comment]
> [23:46:31 INFO]: [HeadHunter] Enabling HeadHunter v2.1.0
> [23:46:31 INFO]: [HeadHunter 2.1.0] === STARTING ACTIVATION ===
> [23:46:33 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_16_R2! Trying to find NMS support
> [23:46:33 WARN]: [NBTAPI] [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
> [23:46:33 ERROR]: Error occurred while enabling HeadHunter v2.1.0 (Is it up to date?)
> de.tr7zw.nbtapi.NbtApiException: Error while calling the method 'null', loaded: false.
> at de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:149) ~[?:?]
> at de.tr7zw.nbtapi.NBTItem.getCompound(NBTItem.java:33) ~[?:?]
> at de.tr7zw.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:468) ~[?:?]
> at de.tr7zw.nbtapi.NBTCompound.setString(NBTCompound.java:68) ~[?:?]
> at me.ByteMagic.HeadHunter.managers.HeadHunter.skulls.MaskSkull.(MaskSkull.java:63) ~[?:?]
> at me.ByteMagic.HeadHunter.managers.HeadHunter.HeadHunterMap.loadMasks(HeadHunterMap.java:115) ~[?:?]
> at me.ByteMagic.HeadHunter.managers.HeadHunter.HeadHunterMap.init(HeadHunterMap.java:69) ~[?:?]
> at me.ByteMagic.HeadHunter.managers.HeadHunter.HeadHunterMap.setActive(HeadHunterMap.java:40) ~[?:?]
> at me.ByteMagic.HeadHunter.managers.HeadHunter.HeadHunterMap.setActive(HeadHunterMap.java:34) ~[?:?]
> at me.ByteMagic.Helix.plugin.BPlugin.activate(BPlugin.java:54) ~[?:?]
> at me.ByteMagic.HeadHunter.Main.preEnable(Main.java:120) ~[?:?]
> at me.ByteMagic.HeadHunter.Main.onEnableInner(Main.java:76) ~[?:?]
> at me.ByteMagic.Helix.plugin.BPlugin.onEnable(BPlugin.java:35) ~[?:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-232]
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-232]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-232]
> at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-232]
> at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-232]
> at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-232]
> at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-232]
> at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-232] at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-232]
> at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
> Caused by: java.lang.NullPointerException
> at de.tr7zw.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:147) ~[?:?]
> ... 22 more
> [23:46:33 INFO]: [HeadHunter] Disabling HeadHunter v2.1.0

Hi Rexy I'd like to Inform you that I myself had the same issue
and figured out how to fix this
Sadly he didn't mention you need to add a plugin called 
(ITEM-NBT-API)
https://www.spigotmc.org/resources/nbt-api.7939/ < Download this make sure Helix & HeadHunters is the same version for support
and then restart it'll then say

[12:21:54 INFO]: [HeadHunter 2.1.0] === STARTING ACTIVATION ===
[12:21:54 WARN]: [HeadHunter] Loaded class de.tr7zw.nbtapi.NBTItem from NBTAPI v2.6.0 which is not a depend, softdepend or loadbefore of this plugin.
[12:21:54 INFO]: [HeadHunter 2.1.0] Item-NBT-Reflection is compatible with this version.
[12:21:54 INFO]: [HeadHunter 2.1.0] === Activation Complete in (131ms) ===

**Comment by alexsatellite** [comment]
Hello, thanks for reporting I saw this already but I couldnt work on it yet as I dont have my computer to work this days

**Comment by alexsatellite** [comment]
Hello, you dont need to add the Item-NTB-API plugin, HeadHunter has it integrated. If you download the new version everything is up to date.
