### ISSUE TITLE
HeadHunter Issue GUI Issue after a Restart

### ISSUE THREAD

**Issue by VideoConnected** [alexsatellite/HeadHunter#27]
Previously I made a report on the fact I couldn't use HeadHunter due to NMS support not being "supported" I fixed that though once I fixed that another problem ended up showing up
after a restart the configuration seems to break the instance.json in the headhunter_conf file
I narrowed it down to this file by deleting it restarting the server letting it regenerate and then restarting once again 
once I deleted the file restarted it worked fine I restarted again it broke
pops up saying
"An internal error occured while attempting to perform this command"
I myself love the Idea of this plugin and have always enjoyed it though It'd be nice for people to have a place like a support discord to go to for quick support on certain things like this

Anyways when I restart after deleting the configuration and run /hh or /headhunter
I receive the Internal error message|
an error in console which goes as followed / below

------------ERROR MESSAGE BELOW--------------------

[13:49:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'hh' in me.ByteMagic.Helix.command.BukkitBCommand(hh)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[server.jar:git-Paper-189]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[server.jar:git-Paper-189]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
at me.ByteMagic.HeadHunter.managers.GUI.HeadGUI.updateMenu(HeadGUI.java:132) ~[?:?]
at me.ByteMagic.HeadHunter.managers.GUI.HeadGUI.createNewMenuInstance(HeadGUI.java:155) ~[?:?]
at me.ByteMagic.HeadHunter.commands.HeadHunterCMD.perform(HeadHunterCMD.java:56) ~[?:?]
at me.ByteMagic.Helix.command.BCommand.execute(BCommand.java:607) ~[?:?]
at me.ByteMagic.Helix.command.BukkitBCommand.execute(BukkitBCommand.java:47) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-189]
... 17 more

----------------------------------------------------------------------------------------------------------------------------

I'm assuming It's something to do with Helix as well though I could be wrong
Please let me know what I and others could do to perhaps fix this

EDIT: 
I'd also like to add that /hh stats as well as /hh rankup both work
the only thing that doesn't would be the GUI

Also Plugin Version is
2.1.0

**Comment by VideoConnected** [comment]
Just adding 

Decided to test it on an empty 1.16.2 Paper Spigot server

No other plugins

Helix
NBT
HeadHunter
Error goes as followed
----------------------------

[21:41:45 INFO]: VideoConnected issued server command: /hh
[21:41:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'hh' in me.ByteMagic.Helix.command.BukkitBCommand(hh)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[server.jar:git-Paper-189]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[server.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[server.jar:git-Paper-189]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
at me.ByteMagic.HeadHunter.managers.GUI.HeadGUI.updateMenu(HeadGUI.java:132) ~[?:?]
at me.ByteMagic.HeadHunter.managers.GUI.HeadGUI.createNewMenuInstance(HeadGUI.java:155) ~[?:?]
at me.ByteMagic.HeadHunter.commands.HeadHunterCMD.perform(HeadHunterCMD.java:56) ~[?:?]
at me.ByteMagic.Helix.command.BCommand.execute(BCommand.java:607) ~[?:?]
at me.ByteMagic.Helix.command.BukkitBCommand.execute(BukkitBCommand.java:47) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-189]
... 17 more

**Comment by alexsatellite** [comment]
As I said in other report, thanks for reporting, I couldnt work on it yet as I dont have my computer to work this days. I'll fix this as soon as I get back my computer.

**Comment by VideoConnected** [comment]
> As I said in other report, thanks for reporting, I couldnt work on it yet as I dont have my computer to work this days. I'll fix this as soon as I get back my computer.

Totally understandable :)
I really like the plugin and love the thought of it
I'd love to see this plugin continue to grow

Thank you for getting back to me

**Comment by alexsatellite** [comment]
Hello, the NMS issue is fixed and available to download from spigot.org.

About the issues with paper, I couldnt get to work it too. I'll try to support paper as soon as I discover why basic things from spigot are missing when I use paper as main dependency

**Comment by VideoConnected** [comment]
> Hello, the NMS issue is fixed and available to download from spigot.org.
> 
> About the issues with paper, I couldnt get to work it too. I'll try to support paper as soon as I discover why basic things from spigot are missing when I use paper as main dependency

Alrighty for sure I've been looking forward to using this 
and I hope It'll work with Paper in the meantime if it doesn't that's 100% fine I can wait for a dependency update :)
