### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by DollarDragon** [alexsatellite/HeadHunter#29]
Hi, I'm getting this error when loading the plugin on my server under openjdk-15, and minecraft paper 1.16.4.
Thanks for the help, it's a great plugin otherwise.

-----------------

[12:49:21 INFO]: [Helix] Enabling Helix v1.0.2
[12:49:21 INFO]: [Helix 1.0.2]  === STARTING ACTIVATION ===
[12:49:21 WARN]: java.lang.NoSuchFieldException: modifiers
[12:49:21 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2569)
[12:49:21 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.<clinit>(ReflectionUtil.java:17)
[12:49:21 WARN]:        at me.ByteMagic.Helix.command.CommandHandler.<init>(CommandHandler.java:155)
[12:49:21 WARN]:        at me.ByteMagic.Helix.command.CommandHandler.<clinit>(CommandHandler.java:19)
[12:49:21 WARN]:        at me.ByteMagic.Helix.plugin.BPlugin.onEnable(BPlugin.java:29)
[12:49:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:49:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:49:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:49:21 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[12:49:21 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:49:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[12:49:21 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setInt(Object, int)" because "me.ByteMagic.Helix.utils.reflection.ReflectionUtil.FIELD_DOT_MODIFIERS" is null
[12:49:21 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.makeAccessible(ReflectionUtil.java:37)
[12:49:21 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.getField(ReflectionUtil.java:67)
[12:49:21 WARN]:        at me.ByteMagic.Helix.command.CommandHandler.<init>(CommandHandler.java:155)
[12:49:21 WARN]:        at me.ByteMagic.Helix.command.CommandHandler.<clinit>(CommandHandler.java:19)
[12:49:21 WARN]:        at me.ByteMagic.Helix.plugin.BPlugin.onEnable(BPlugin.java:29)
[12:49:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:49:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:49:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:49:21 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[12:49:21 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:49:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[12:49:21 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setInt(Object, int)" because "me.ByteMagic.Helix.utils.reflection.ReflectionUtil.FIELD_DOT_MODIFIERS" is null
[12:49:21 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.makeAccessible(ReflectionUtil.java:37)
[12:49:21 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.getField(ReflectionUtil.java:67)
[12:49:21 WARN]:        at me.ByteMagic.Helix.command.CommandHandler.<clinit>(CommandHandler.java:149)
[12:49:21 WARN]:        at me.ByteMagic.Helix.plugin.BPlugin.onEnable(BPlugin.java:29)
[12:49:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:49:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:49:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:49:21 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[12:49:21 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:49:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[12:49:21 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setInt(Object, int)" because "me.ByteMagic.Helix.utils.reflection.ReflectionUtil.FIELD_DOT_MODIFIERS" is null
[12:49:21 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.makeAccessible(ReflectionUtil.java:37)
[12:49:21 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.getField(ReflectionUtil.java:67)
[12:49:21 WARN]:        at me.ByteMagic.Helix.command.CommandHandler.<init>(CommandHandler.java:155)
[12:49:21 WARN]:        at me.ByteMagic.Helix.plugin.BPlugin.onEnable(BPlugin.java:29)
[12:49:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:49:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:49:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:49:21 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[12:49:21 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940)
[12:49:21 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:49:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[12:49:21 INFO]: [Helix 1.0.2]  Activating Helix 1.0.2
[12:49:21 INFO]: [Helix 1.0.2]  === Activation Complete in (111ms) ===

---------

[12:49:30 INFO]: [HeadHunter 2.1.1]  === STARTING ACTIVATION ===
[12:49:30 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setInt(Object, int)" because "me.ByteMagic.Helix.utils.reflection.ReflectionUtil.FIELD_DOT_MODIFIERS" is null
[12:49:30 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.makeAccessible(ReflectionUtil.java:37)
[12:49:30 WARN]:        at me.ByteMagic.Helix.utils.reflection.ReflectionUtil.getField(ReflectionUtil.java:67)
[12:49:30 WARN]:        at me.ByteMagic.Helix.command.CommandHandler.<init>(CommandHandler.java:155)
[12:49:30 WARN]:        at me.ByteMagic.Helix.plugin.BPlugin.onEnable(BPlugin.java:29)
[12:49:30 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:49:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:49:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:49:30 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[12:49:30 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[12:49:30 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)
[12:49:30 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[12:49:30 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940)
[12:49:30 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:49:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)

--------------

**Comment by alexsatellite** [comment]
The plugin doesnt support yet PaperSpigot as they changed a lot of things from Spigot. Im still looking into it as I know that paper performs a bit better than the Spigot.

**Comment by DollarDragon** [comment]
Ok, do you have a time scale for when it might be compatible ?
Thanks for the quick reply.

**Comment by YTPSDanDie** [comment]
I know from experience that it is a big job to change the coding from one to the other, let me know if you managed to update to accept paper please.
