### ISSUE TITLE
Sign shop issue

### ISSUE THREAD

**Issue by Xsm-Cobra** [alexsatellite/HeadHunter#37]
When buying a spawner it charges the player but doesnt give them the spawner

**Comment by Xsm-Cobra** [comment]
Im using 1.8.8 spigot and epic spawners

**Comment by Xsm-Cobra** [comment]
18.03 00:35:29 [Server] ERROR Could not pass event PlayerInteractEvent to HeadHunter v2.0.3
18.03 00:35:29 [Server] INFO org.bukkit.event.EventException
18.03 00:35:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
18.03 00:35:29 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
18.03 00:35:29 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/songoda/epicspawners/api/EpicSpawnersAPI
18.03 00:35:29 [Server] INFO at me.ByteMagic.HeadHunter.support.EpicSpawnerSupport.giveSpawner(EpicSpawnerSupport.java:24) ~[?:?]
18.03 00:35:29 [Server] INFO at me.ByteMagic.HeadHunter.support.SpawnerSupport.giveSpawner(SpawnerSupport.java:25) ~[?:?]
18.03 00:35:29 [Server] INFO at me.ByteMagic.HeadHunter.engine.EngineSign.OnInteract(EngineSign.java:147) ~[?:?]
18.03 00:35:29 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
18.03 00:35:29 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
18.03 00:35:29 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
18.03 00:35:29 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
18.03 00:35:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
18.03 00:35:29 [Server] INFO ... 17 more 

You might need this
